### ISSUE TITLE
Problem selection

### ISSUE THREAD

**Issue by karanjadhav2508** [karanjadhav2508/kqsse17#1]
## Visitor management
- Improper/incomplete logging in and out of visitors in different places : libraries, residence halls, organizations
- varying consequences : insufficient visibility/tracking of visitors, security compromise
- white house also has this [problem](https://www.publicintegrity.org/2011/04/13/4115/white-house-visitor-logs-riddled-holes)
- [literature review](https://scholar.google.com/scholar?q=visitor+logging&btnG=&hl=en&as_sdt=0%2C34&oq=visitor+) in progress

**Comment by smscoggi** [comment]
# Attendance Management

- Professors keeping track of students attending class and other similar activities
- This is better than Visitor Management because of more available literature

**Comment by karanjadhav2508** [comment]
- Attendance management system under consideration
- Literature review in progress
- [uptil now](https://github.com/karanjadhav2508/kqsse17/blob/master/ideas/attendance_mgmt.MD)

**Comment by karanjadhav2508** [comment]
Adequate literature found. Attendance management system finalized as the topic a few days back.
Closing issue.
