### ISSUE TITLE
Literature review

### ISSUE THREAD

**Issue by karanjadhav2508** [karanjadhav2508/kqsse17#2]

**Comment by smscoggi** [comment]
Here are some links to relevant papers and descriptions. More concrete summaries will come later.


http://ieeexplore.ieee.org.prox.lib.ncsu.edu/document/6422874/

o Visitor Management System by Applying the Model of UTAUT (2012)

o Talks of research done concerning user acceptance of particular visitor management

systems

 http://search.proquest.com.prox.lib.ncsu.edu/docview/222676751?pq-origsite=summon

o VISITOR MANAGEMENT SYSTEMS

o Blades, Marleah. Security Dealer; Melville29.11 (Nov 2007): 46,48-49.

o Explains why visitor management is important, and ideas of how it can be implemented.


http://search.proquest.com.prox.lib.ncsu.edu/docview/1767945075/fulltext/CECE0130CB541F1

PQ/1?accountid=12725

o Computer Peripherals Companies; Patent Application Titled &quot;Visitor Information System,

Management Server, and Visitor Information Management Method&quot; Published Online

(USPTO 20160042131)

o Information Technology Newsweekly; Atlanta (Mar 1, 2016): 1385.

o Patent application for system that reduces wait time for large groups of visitors

**Comment by karanjadhav2508** [comment]
- Problems found for this idea. Possibly numbers/data needed to back this up for the report/presentation
- [2 solutions](https://github.com/karanjadhav2508/kqsse17/blob/master/ideas/attendance_mgmt.MD) found. "Inspired" implementations seem quite possible at this point
- Both app based owing to google API
- Further lit review in progress

**Comment by smscoggi** [comment]
For the Attendance Management Problem here are some reviews/ summaries/ analysis of relevant papers-

[Paper Reviews.docx](https://github.com/karanjadhav2508/kqsse17/files/722403/Paper.Reviews.docx)

**Comment by karanjadhav2508** [comment]
Literature review completed. Closing issue.
