### ISSUE TITLE
Database + GUI 

### ISSUE THREAD

**Issue by alokozai** [karanjadhav2508/kqsse17#21]
in process reviewing codes for GUI+Database!! 
How it works??
Get the functionalities in place????
What else???
Did not understand?????

**Comment by alokozai** [comment]
a complicated inter-connectivity of how the voice will inputs will be saved and then stored into a database followed by retrieval for comparison.........I Can Do It.........

**Comment by smscoggi** [comment]
Post some code and maybe I can help? You are using Java applets right? What are you using for database?

**Comment by alokozai** [comment]
I am reading about SQL. Once I develop some substantial implementation and if I faced problem surely i will share with you and seek help. Thanks Samantha.

**Comment by smscoggi** [comment]
What are you using for IDE for your program? that will impact how you could better implement database connection.

**Comment by smscoggi** [comment]
**Here is the dbconnection class I used for connecting to MySQL from java. This is after connecting NetBeans IDE to the database, and downloading the MySQL connection driver MySQL-connector-java-5.1.40-bin.jar, wherever I need to use the connection, I would instantiate this class, and use the query method to send querys and return results if needed **

If this helps please let me know

package engagetendance;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author Sam
 */
public class DBconnection {
    Connection con;
    
       DBconnection(){
           
           try{
           String host = "jdbc:mysql://localhost:3306/tendancedb?zeroDateTimeBehavior=convertToNull";
           String uName = "root";
           String uPass = "root";
           
           con = DriverManager.getConnection(host, uName, uPass);
           }
           catch(SQLException err){
               System.out.println(err.getMessage());
           }
           
       }
       
       
       public ResultSet query(String q){
           try{
               Statement stmt = con.createStatement();
               
               String SQL = "SELECT* FROM users;";
               ResultSet rs = stmt.executeQuery(SQL);
               
               return rs;
               
           }
           catch(SQLException err){
               System.out.println(err.getMessage());
               return null;
           }
           
       }
    
}

**Comment by smscoggi** [comment]
Correction for query method, needed to change it so q was executed instead of sql string which was temporary.

public ResultSet query(String q){
    try{
        Statement stmt = con.createStatement();
       
        ResultSet rs = stmt.executeQuery(q);
        
        return rs;
        
    }

**Comment by smscoggi** [comment]
Any luck with your database connection?

**Comment by alokozai** [comment]
I am working on it and will complete it. This helps a lot and gives much sense. I had also reviewed such code. But I am also reviewing some video tutorials so both helps. I will update you soon :)

**Comment by alokozai** [comment]
success in saving data including voice in database.
