### ISSUE TITLE
Log in implementation

### ISSUE THREAD

**Issue by smscoggi** [karanjadhav2508/kqsse17#23]
How do you all handle login? Face rec. didn't have any at all, but it should for admin/professors at least?

**Comment by alokozai** [comment]
Login: the instructor will directly open to GUI which will include functionalities to record and check attendance. I dont have login page. Which can be done but for now I am focusing on how to put the database together. I am also thinking about Reporting, as I have to retrieve the data from database which will be used to give daily reporting of attendance.

**Comment by alokozai** [comment]
I believe that we are all on track, after this upcoming solution work it will all give more sense.

**Comment by karanjadhav2508** [comment]
I haven't implemented login yet. I'm working on the DB part for attendance recording.
Will get to login after this, once all core functionality is in place.

**Comment by alokozai** [comment]
Great. For now we need to focus on the report for this Tuesday. Do you guys have any adivce/suggestions for this weeks report?

**Comment by karanjadhav2508** [comment]
It's here Qaiss : [report issue](https://github.com/karanjadhav2508/kqsse17/issues/26)

**Comment by smscoggi** [comment]
Login and role customization completed, (except for hashing and encrypting password).

**Comment by smscoggi** [comment]
For right now, will not create SQL script for git hub use.
