### ISSUE TITLE
Professor side

### ISSUE THREAD

**Issue by smscoggi** [karanjadhav2508/kqsse17#25]
How will the view from the professor be different? what capabilities are you giving them vs. the students?

**Comment by smscoggi** [comment]
For Engagement implementation:


=>Can Set
  -quiz schedule (mw,tr,mwf,f...) for particular class
  -quizes: date, duration, type, delete, questions, correct answers.
Time limit: 1st ten minutes vs. whole class (would vary with professor)
  -number of quizes(days) one can miss before they should be droped, in which a message will pop up denoting all such students in said class that should be dropped from the course.

 =>Can navigate between different classes quickly
 =>Can place settings on individual classes (such as schedule, add/remove students [could have security concerns here however])
 =>Can see
  -all past quiz results by date
  -all attendence scores by student
  -scores will be primarily be determined by whether student took quiz (clicking the "I'm here" button), not by actual quiz grade

**Comment by smscoggi** [comment]
Professor abilities that may relate to both other implementations:

=>Can navigate between different classes quickly
=>Can place settings on individual classes (such as schedule, add/remove students [could have security concerns here however])
=>Can see
-all attendance scores by student or date

* Can add or remove student? Though this should be up to the registrar, so maybe not...

**Comment by karanjadhav2508** [comment]
I'm doing an instructor view only for now. Since there is no interaction required from the students in face recognition, the student's view isn't all that important. Because it will only contain attendance viewing, plus recognition won't be a feature given to the student.

**Comment by alokozai** [comment]
Me and Karan are kind of similar. Instructor will have access to the program. 
Professor:
1. Before semester starts all details are entered in the system and voice recorded into the database. 
2. Each student says his name
3. Compared into the database 
4. True or false values leads to present or absent. 
5. Report (confusion so far) 
6. Exit

**Comment by smscoggi** [comment]
We have discussed how each of us approaches professor relationship to applications.

-Closing issue
