### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by smscoggi** [karanjadhav2508/kqsse17#26]
We each need to write one page report about our implementations.

Use requirements, functionality, and other documentation created so far to create them.

**Comment by alokozai** [comment]
great. Thanks for the clarification Samantha.

**Comment by alokozai** [comment]
Thank you Karan. It helps.

**Comment by alokozai** [comment]
If I have further questions I will hit you guys up here :)

**Comment by alokozai** [comment]
Please include my diagram which is in the report. Thanks a lot guys.

**Comment by smscoggi** [comment]
Where is it? we can't find it?

**Comment by smscoggi** [comment]
Report has been completed and link added to class spreadsheet.
