### ISSUE TITLE
Brainstorming for Feb SE Project

### ISSUE THREAD

**Issue by alokozai** [karanjadhav2508/kqsse17#6]
1. Coming up with plan for Project 2.
2. Any ideas?
3. Any magic?
4. What amazing things we can do with our projects?
5. Anything else :)

**Comment by alokozai** [comment]
Team: I believe we need to expedite the process :)

**Comment by karanjadhav2508** [comment]
So last class Dr. Menzies allotted us 3 implementations. They are:
- Facial recognition
- One time password
- Quizzes/in class exercise

Me and Samantha were thinking even voice recognition will be a good idea and the API seems to exist for Android. But will need to check in detail.
Let's meet today as discussed.
One thing that seems definite is that everyone needs to start learning Android development.

**Comment by alokozai** [comment]
great:)

**Comment by karanjadhav2508** [comment]
Hey guys. So we've added the milestones for Feb on Tuesday as required. Let's meet today and discuss on the details of this plan on how we want to handle all 3 implementations amongst ourselves.
