### ISSUE TITLE
Understanding the voice recognition API

### ISSUE THREAD

**Issue by alokozai** [karanjadhav2508/kqsse17#8]
Research about the voice API.

**Comment by karanjadhav2508** [comment]
Let's get to this in a couple of days after we've familiarized ourselves in working with Android.

**Comment by alokozai** [comment]
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech

**Comment by alokozai** [comment]
The google voice API. Progress in learning and understanding the API.

**Comment by alokozai** [comment]
GUI functional uploaded
